export const relacaoCidades = [
  { estabelecimento_municipio_nome: "PORTO ALEGRE" },
  { estabelecimento_municipio_nome: "IGREJINHA" },
  { estabelecimento_municipio_nome: "PAROBE" },
  { estabelecimento_municipio_nome: "TRES COROAS" },
  { estabelecimento_municipio_nome: "SANTA MARIA" },
  { estabelecimento_municipio_nome: "SANTA CLARA" },
  { estabelecimento_municipio_nome: "GRAMADO" },
  { estabelecimento_municipio_nome: "CANELA" },
  { estabelecimento_municipio_nome: "TAQUARA" },
  { estabelecimento_municipio_nome: "NOVA PETROPOLIS" },
  { estabelecimento_municipio_nome: "NOVA TRAMANDAI" },
  { estabelecimento_municipio_nome: "TORRES" },
  { estabelecimento_municipio_nome: "URUGUAIANA" },
  { estabelecimento_municipio_nome: "NOVO HAMBURGO" },
  { estabelecimento_municipio_nome: "CANOAS" },
  { estabelecimento_municipio_nome: "SAO LEOPOLDO" },
  { estabelecimento_municipio_nome: "IVOTI" },
  { estabelecimento_municipio_nome: "SAPIRANGA" },
  { estabelecimento_municipio_nome: "CAPAO DA CANOA" },
  { estabelecimento_municipio_nome: "TRAMANDAI" },
  { estabelecimento_municipio_nome: "RIO GRANDE" },
  { estabelecimento_municipio_nome: "FELIZ" },
];

export const relacaoDados = [
  {
    document_id: "fa79e0f9-8459-4459-85e3-826605ccfb9d-i0b0",
    paciente_id: 0,
    paciente_idade: 66,
    paciente_dataNascimento: "1954-09-29",
    paciente_enumSexoBiologico: "F",
    paciente_racaCor_codigo: 1,
    paciente_racaCor_valor: "BRANCA",
    paciente_endereco_coIbgeMunicipio: 431490,
    paciente_endereco_coPais: 10,
    paciente_endereco_nmMunicipio: "PORTO ALEGRE",
    paciente_endereco_nmPais: "BRASIL",
    paciente_endereco_uf: "RS",
    paciente_endereco_cep: 91570,
    paciente_nacionalidade_enumNacionalidade: "B",
    estabelecimento_valor: 2264838,
    estabelecimento_razaoSocial: "PREFEITURA MUNICIPAL DE PORTO ALEGRE",
    estalecimento_noFantasia: "UNIDADE DE SAUDE SAO CARLOS",
    estabelecimento_municipio_codigo: 431490,
    estabelecimento_municipio_nome: "PORTO ALEGRE",
    estabelecimento_uf: "RS",
    vacina_grupoAtendimento_codigo: 202,
    vacina_grupoAtendimento_nome: "Pessoas de 65 a 69 anos",
    vacina_categoria_codigo: 2,
    vacina_categoria_nome: "Faixa Etária",
    vacina_lote: "210214",
    vacina_fabricante_nome: "SINOVAC/BUTANTAN",
    vacina_fabricante_referencia: "Organization/61189445000156",
    vacina_dataAplicacao: "2021-05-20",
    vacina_descricao_dose: "2ª Dose",
    vacina_codigo: 86,
    vacina_nome: "COVID-19 SINOVAC/BUTANTAN - CORONAVAC",
    sistema_origem: "Novo PNI\n",
  },
  {
    document_id: "bfe786ac-24af-4cc9-be07-30734738669b-i0b0",
    paciente_id: 618,
    paciente_idade: 39,
    paciente_dataNascimento: "1981-11-01",
    paciente_enumSexoBiologico: "F",
    paciente_racaCor_codigo: 3,
    paciente_racaCor_valor: "PARDA",
    paciente_endereco_coIbgeMunicipio: 431490,
    paciente_endereco_coPais: 10,
    paciente_endereco_nmMunicipio: "PORTO ALEGRE",
    paciente_endereco_nmPais: "BRASIL",
    paciente_endereco_uf: "RS",
    paciente_endereco_cep: 91230,
    paciente_nacionalidade_enumNacionalidade: "B",
    estabelecimento_valor: 3729559,
    estabelecimento_razaoSocial: "SECRETARIA MUNICIPAL DE SAUDE",
    estalecimento_noFantasia: "SECRETARIA MUNICIPAL DE SAUDE DE PORTO ALEGRE",
    estabelecimento_municipio_codigo: 431490,
    estabelecimento_municipio_nome: "PORTO ALEGRE",
    estabelecimento_uf: "RS",
    vacina_grupoAtendimento_codigo: 201,
    vacina_grupoAtendimento_nome: "Pessoas de 18 a 64 anos",
    vacina_categoria_codigo: 2,
    vacina_categoria_nome: "Faixa Etária",
    vacina_lote: "210336",
    vacina_fabricante_nome: "SINOVAC/BUTANTAN",
    vacina_fabricante_referencia: "Organization/61189445000156",
    vacina_dataAplicacao: "2021-08-02",
    vacina_descricao_dose: "1ª Dose",
    vacina_codigo: 86,
    vacina_nome: "COVID-19 SINOVAC/BUTANTAN - CORONAVAC",
    sistema_origem: "Novo PNI\n",
  },
  {
    document_id: "fa7cb00b-a6cf-4daa-8328-99145f0b2c1a-i0b0",
    paciente_id: 0,
    paciente_idade: 38,
    paciente_dataNascimento: "1984-07-05",
    paciente_enumSexoBiologico: "M",
    paciente_racaCor_codigo: 99,
    paciente_racaCor_valor: "SEM INFORMACAO",
    paciente_endereco_coIbgeMunicipio: 431690,
    paciente_endereco_coPais: 10,
    paciente_endereco_nmMunicipio: "SANTA MARIA",
    paciente_endereco_nmPais: "BRASIL",
    paciente_endereco_uf: "RS",
    paciente_endereco_cep: 97015,
    paciente_nacionalidade_enumNacionalidade: "B",
    estabelecimento_valor: 2237571,
    estabelecimento_razaoSocial: "HOSPITAL NOSSA SENHORA DA CONCEICAO SA",
    estalecimento_noFantasia: "HOSPITAL NOSSA SENHORA DA CONCEICAO SA",
    estabelecimento_municipio_codigo: 431490,
    estabelecimento_municipio_nome: "PORTO ALEGRE",
    estabelecimento_uf: "RS",
    vacina_grupoAtendimento_codigo: 912,
    vacina_grupoAtendimento_nome: "Médico",
    vacina_categoria_codigo: 9,
    vacina_categoria_nome: "Trabalhadores de Saúde",
    vacina_lote: "213J21A",
    vacina_fabricante_nome: "JANSSEN",
    vacina_fabricante_referencia: "Organization/30587",
    vacina_dataAplicacao: "2022-07-19",
    vacina_descricao_dose: "2º Reforço",
    vacina_codigo: 88,
    vacina_nome: "COVID-19 JANSSEN - Ad26.COV2.S",
    sistema_origem: "Novo PNI\n",
  },
];
