import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [cidades, setCidades] = useState(null);

  const chamaApi = async () => {
    const resultado = await fetch("/api/get_nomes_cidades");
    console.log(await resultado.json());

    const data = {
      cidade: "IGREJINHA",
    };

    const testePost = await fetch("/api/filtrar_vacinas", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(data),
    });

    console.log(await testePost.json());
    setCidades(await resultado.json());
  };

  useEffect(() => {
    chamaApi();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Projeto Integrador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cidades && cidades.map((cidade, index) => <h1 key={index}>{cidade.estabelecimento_municipio_nome}</h1>)}
    </div>
  );
}
